### ISSUE TITLE
[Docs] Add downstream tasks descriptions/useful information

### ISSUE THREAD

**Issue by SolomidHero** [s3prl/s3prl#70] opened 2021-01-28 15:19 UTC
Hi! As I remember, in the past versions of main readme, there were small descriptions for downstream tasks used for finetuning/etc. Now the `downstream/README.md` lacks of information about plenty of tasks that might be used. 

`upstream/README.md` points for tasks information (in **How to specify your upstream** section) to `downstream/README.md` page, but it is poor of information:

> For example, this is how you specifing them in the command of downstream training scripts (more details of downstream tasks can be found here:

For example, there are tasks which use different datasets for train process (libri or timit), and it is not clear how to prepare data for finetuning.

Of course, this information might be included sometime, so this issue is more about docs TODO list.

**Comment by yuanfeng-yl** [comment] 2021-03-01 05:27
I have similar confusions. It is really difficult to derive the structure and function of downstream tasks from the name alone.

**Comment by leo19941227** [comment] 2021-03-08 13:43
Hi!

Sorry for the lack for the documentation :(
We have a detailed documentation internally, but since we are still developing the downstream part so we not yet release it to the public. We are really sorry for the inconvenience.
This issue will be resolved in at most one month.
Thanks for your patience :)

**Comment by leo19941227** [comment] 2021-05-06 11:48
Hi,

We have released the downstream implementations and their documentation for reproducing [SUPERB: Speech processing Universal PERformance Benchmark](https://arxiv.org/abs/2105.01051) at the `downstream/` folder. I believe this issue is resolved. Thanks for you patient!

**Closed by leo19941227** 2021-05-06 11:48 UTC
Labels: documentation
