### ISSUE TITLE
Bug(?) when batching wav files that are too short

### ISSUE THREAD

**Issue by trangham283** [s3prl/s3prl#80] opened 2021-02-10 21:48 UTC
Hello, 

I'm running into issues when using upstream models on audio files that are too short. The model I'm using is `audio_albert` and the process is killed when the batch includes short waveforms but is processed ok individually. 

For example, for a batch with wav with lengths `[torch.Size([98399]), torch.Size([311360]), torch.Size([70561]), torch.Size([16801]), torch.Size([5280]), torch.Size([30240]), torch.Size([15040]), torch.Size([1280])]`, the program is killed without further error messages when I run `model(wavs)`, but I am able to run `model(wavs[0])`, `model(wavs[7])` etc without issue. 

I think at least a more informative error message or some sort of warning when input waveforms are too short would help. 

Thanks for doing all this, great codebase!

**Comment by trangham283** [comment] 2021-02-11 06:05
Actually, now that I look at it, the offending element might have been the long one (`torch.Size([311360])`). Running the model over it by itself is fine, but in a batch might have caused everything to crash. Still, the only "report" I got was a `Killed`, instead of an OOM error message.

**Comment by leo19941227** [comment] 2021-02-14 15:53
Hi,

Thank you for pointing out this error, and I will check this ASAP.

**Comment by trangham283** [comment] 2021-02-18 19:43
Hi @leo19941227 

Thank you for looking into this. When I ran into this error I was using a Linux machine (x86_64, Ubuntu). It has GTX 108 GPUs but I don't think the embedding extraction was using GPUs (I might be mistaken if your code allows it to use GPUs automatically).

**Comment by leo19941227** [comment] 2021-02-19 04:34
Hey! We use GPU as default since some pretrained model will be extremely slow to extract representation without GPU. Can you share the command to reproduce this error?

**Comment by trangham283** [comment] 2021-02-19 06:17
Hi! 

Sure, here it is:

```
import torch
import random
random.seed(0)

model = torch.hub.load("s3prl/s3prl", "audio_albert")
lengths = [3898720, 98399, 311360, 70561, 16801, 5280, 30240, 15040, 1280]
wavs = []

for i in lengths:
    wavs.append(torch.rand(i))

for wav in wavs:
    f = model([wav])
    print(f[0].shape)

feats = model(wavs)
print([x.shape for x in feats])
```

Output:

```
/home/ICT2000/ttran/miniconda3/lib/python3.8/site-packages/torchaudio/backend/utils.py:53: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  warnings.warn(
[hubconf] can not import upstream.decoar.hubconf: No module named 'mxnet'... Pass.
[hubconf] can not import upstream.wav2vec2.hubconf: No module named 'fairseq'... Pass.
[hubconf] can not import upstream.vq_wav2vec.hubconf: No module named 'fairseq'... Pass.
[hubconf] can not import upstream.wav2vec.hubconf: No module named 'fairseq'... Pass.
[hubconf] can not import upstream.wav2vec2_ft.hubconf: No module named 'fairseq'... Pass.
[hubconf] can not import upstream.pase.hubconf: No module named 'pase'... Pass.
Using cache found in /home/ICT2000/ttran/.cache/torch/hub/s3prl_cache/55805839eb58b56972be4a9994ca99c862d2572cfd74ae26c916e8ced5d45a7a
for https://www.dropbox.com/s/3wgynxmod77ha1z/states-1000000.ckpt?dl=0
/home/ICT2000/ttran/miniconda3/lib/python3.8/site-packages/torchaudio/functional.py:317: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (128) may be set too high. Or, the value for `n_freqs` (201) may be set too low.
  warnings.warn(
/home/ICT2000/ttran/miniconda3/lib/python3.8/site-packages/torch/functional.py:515: UserWarning: stft will require the return_complex parameter be explicitly  specified in a future PyTorch release. Use return_complex=False  to preserve the current behavior or return_complex=True to return  a complex output. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:653.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore
/home/ICT2000/ttran/miniconda3/lib/python3.8/site-packages/torch/functional.py:515: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:590.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore
torch.Size([24368, 768])
torch.Size([615, 768])
torch.Size([1947, 768])
torch.Size([442, 768])
torch.Size([106, 768])
torch.Size([34, 768])
torch.Size([190, 768])
torch.Size([95, 768])
torch.Size([9, 768])
Killed
```

As you can see processing the signals individually is ok, but crashed in a batch. I'm guessing it's OOM but the error returned is simply "Killed"

Thanks for looking into this!

**Comment by swarajdalmia** [comment] 2021-02-22 06:17
Did anyone find a solution for this ? I'm running into this issue for the other models too. 
I tried wav2vec2 and vq_wav2vec and the generating reps call just gets killed without any error messages.

**Comment by andi611** [comment] 2021-02-22 16:25
> Hi!
> 
> Sure, here it is:
> 
> ```
> import torch
> import random
> random.seed(0)
> 
> model = torch.hub.load("s3prl/s3prl", "audio_albert")
> lengths = [3898720, 98399, 311360, 70561, 16801, 5280, 30240, 15040, 1280]
> wavs = []
> 
> for i in lengths:
>     wavs.append(torch.rand(i))
> 
> for wav in wavs:
>     f = model([wav])
>     print(f[0].shape)
> 
> feats = model(wavs)
> print([x.shape for x in feats])
> ```

Hi,

I think the problem is you are doing this on CPU instead of GPU.
You can simply add `.to('cuda')` after `model` and every input to load them to your GPU.
An example of doing extraction on GPU is given [here](https://github.com/s3prl/s3prl/blob/master/upstream/audio_albert/example_extract.py).
Let us know if you still encounter this problem after moving to GPU, thanks!

Andy

**Comment by trangham283** [comment] 2021-02-22 19:02
Hi @andi611 

Moving everything on GPU resulted in a more informative error message (OOM). So the issue with the process being "killed" seems to be that CPU doesn't have enough memory either, but doesn't give an informative error message?

Thanks for looking into this.

**Closed** 2021-02-26 00:27 UTC
