### ISSUE TITLE
train downstream ASR using own upstream

### ISSUE THREAD

**Issue by zyzpower** [s3prl/s3prl#69] opened 2021-01-28 14:43 UTC
Hi, I want to use the pertained model for downstream ASR task, however in the s3prl/downstream/asr/feat/ directory, there is no config file, is the ASR task properly configured? Thanks.

**Comment by aayushsingla** [comment] 2021-01-29 03:02
Hey, I'm facing a similar issue in using asr for downstream. can someone please help me with this?

**Comment by leo19941227** [comment] 2021-01-29 08:12
Hi,

Since ASR is a complicated system including LM training and beam search decoding during testing. Instead of reinventing the wheel on this repo, we decided to incorporate s3prl pretrained models into the framework of an existing well-organized ASR repo [Alexander-H-Liu/End-to-end-ASR-Pytorch](https://github.com/Alexander-H-Liu/End-to-end-ASR-Pytorch), which is created by a senior member from our lab. Currently we create a fork from that repo to support the pretrained models: [s3prl/End-to-end-ASR-Pytorch](https://github.com/s3prl/End-to-end-ASR-Pytorch). We modified several components to enable finetuning:

- Delay the feature extraction part from dataloader to training loop, and accelerate it by GPU either for fbank extraction or pretrained feature extraction.
- Support distributed data parallel to enable large batch size finetuning, since some pretrained models can be huge like wav2vec2

One can refer to the README in [s3prl/End-to-end-ASR-Pytorch](https://github.com/s3prl/End-to-end-ASR-Pytorch) for more details and hope this answer your question!
Thanks!

Sincerely,
Leo

**Comment by zyzpower** [comment] 2021-01-29 13:31
Hi Leo, thanks for the reply. I read the End-to-end-ASR-Pytorch project, but I do not fully understand how to link up pertaining with the ASR task. I guess the pertained model is slot in before step 2 training the end-to-end ASR? Will there be a detailed procedure?

**Comment by leo19941227** [comment] 2021-01-29 13:48
Hi, 

The pretrained model is plugged at [here](https://github.com/s3prl/End-to-end-ASR-Pytorch/blob/a58a2d67c2cb089dd8cd821b91487b9a3d871980/bin/train_asr.py#L47)  in [s3prl/End-to-end-ASR-Pytorch](https://github.com/s3prl/End-to-end-ASR-Pytorch). The pipeline is like:

1. The dataloader prepares batches of waveforms.
2. The pretrained upstream model extracts features from the input waveforms.
3. The downstream ASR model uses pretrained features as input to train CTC or LAS loss (or hybrid).

There might not be detailed procedure in one or two months, but for ASR since the doc is quite comprehensive in the original repo, so it might work for you after some code tracing. You can search for `Finetune pretrained models with multiple GPUs` in the README.md of [s3prl/End-to-end-ASR-Pytorch](https://github.com/s3prl/End-to-end-ASR-Pytorch), that might be the most relevant part for you.

Sincerely,
Leo

**Comment by zyzpower** [comment] 2021-02-01 04:34
Thanks Leo, I see the upsteam model is loaded withupstream = torch.hub.load('s3prl/s3prl', 'tera')

**Comment by leo19941227** [comment] 2021-02-01 05:22
Oh I get it! If you wish to use your own pretrained model, indeed you

**Comment by leo19941227** [comment] 2021-02-01 06:12
Hi!

This is a good point! I haven't thought about this situation. This indeed shall be improved, to make the customized pretrained models easily evaluated. I will dive into this and thank you for the insightful comments. This is a must have feature.

Sincerely,
Leo

**Comment by zyzpower** [comment] 2021-02-01 09:35
Thanks Leo, or maybe you can share how you save the pretrained model to torch.hub

**Comment by leo19941227** [comment] 2021-02-02 12:20
Hi,

Actually it is quite straight forward! You just have to create your own repository with a `hubconf.py` at the root of the repository, and then `torch.hub` will automatically locate your repo (based on the repo name you pass to `torch.hub.load`) and call the function written in your `hubconf.py` where you decide what model to return.
Here is the reference: https://pytorch.org/docs/stable/hub.html

**Comment by zyzpower** [comment] 2021-02-04 06:17
Hi Leo, I tried write hubconf.py to upload the self pertained model, but I do not know how should I initialise the model. Below is the hubconf.py I write, but it has the error of "NameError: name 'model' is not defined". Should I initialise it from the class runner in s3prl/pretrain/runner.py?

import os
import torch
dependencies = ['torch']

def mkj(*args, **kwargs):
    """
    pretrained libri100 mockingjay
    """
    dirname = os.path.dirname(__file__)
    checkpoint = os.path.join(dirname, 'result/pretrain/mkj_100/states-epoch-100.ckpt')
    state_dict = torch.load(checkpoint)
    model.load_state_dict(state_dict)
    return model

**Comment by leo19941227** [comment] 2021-02-05 00:30
Hey,

Are you also using this toolkit for the pretraining? If this is true, then there might be a simpler solution.
In our ASR repo you can try using arguments like:
```
python3 main.py --config config/libri/finetune.yaml --upstream mockingjay_local --upstream_ckpt [your path]
```

**Comment by zyzpower** [comment] 2021-02-08 15:12
Hi Leo, I am not too sure where is the main.py file located.
I try to use the pertained model for another ASR toolkit. I load the pretrained model using " torch.load(ckpt_pth, map_location='cpu') ". However, there is always an error of 
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
I run shell file to call python function, is this the reason?

**Comment by leo19941227** [comment] 2021-02-16 20:23
Hi,

Could you fork that repo and make your change visible on GitHub? (create a minimal shell script to reproduce your issue will be nice.)
Perhaps I need more information to understand the situation.

Thanks!

**Comment by leo19941227** [comment] 2021-03-03 08:40
We are including downstream ASR into s3prl currently on asr branch, so I am closing this issue. It will be soon merged into master, thank you for your patience.

**Closed** 2021-03-03 08:40 UTC
