### ISSUE TITLE
Upstream request: wavLM

### ISSUE THREAD

**Issue by bagustris** [s3prl/s3prl#245] opened 2021-11-09 02:37 UTC
I see WavLM now topped all of the SUPERB tasks (10 tasks). So, I would like to request to add this audio embedding to upstream.

Paper: https://arxiv.org/pdf/2110.13900.pdf
Code/Model: https://github.com/microsoft/unilm/tree/master/wavlm

Currently, only base and base+ models are available; the large version will be added soon.

**Comment by MarkWuNLP** [comment] 2021-11-10 06:26
> I see WavLM now topped all of the SUPERB tasks (10 tasks). So, I would like to request to add this audio embedding to upstream.
> 
> Paper: https://arxiv.org/pdf/2110.13900.pdf Code/Model: https://github.com/microsoft/unilm/tree/master/wavlm
> 
> Currently, only base and base+ models are available; the large version will be added soon.

Hi, I am Yu Wu, the author of WavLM. I am glad to add the WavLM to the upstream. We are glad to offer any help that we can provide.  Let's wait the reply from the repo owner.

**Comment by bagustris** [comment] 2021-11-10 07:49
Hi @MarkWuNLP, 

That will be a great contribution. I think the owner will be happy with that, right @leo19941227 ?
This repo is very open; I make several contributions and they always accept it.

I already have the unispeechSat model in my local's upstream. I may make PR for this upstream too.

**Comment by leo19941227** [comment] 2021-11-10 23:13
Hi @bagustris and @MarkWuNLP !

Cool! We are happy to have WavLM and UnispeechSAT in S3PRL!
Would it be okay for @bagustris to make PR for these two models and perhaps @MarkWuNLP could help review it?
Many thanks!

Sincerely,
Leo

**Comment by bagustris** [comment] 2021-11-11 00:49
Thanks! however, I have a problem with my implementation of WavLM  (I think because of fairseq version), so I would let @MarkWuNLP to do this PR as he is the original author. We may have someone to review it.

**Comment by MarkWuNLP** [comment] 2021-11-11 02:47
Hi @bagustris  and  @leo19941227 ,
   I discussed the PR with Sanyuan Chen (first author of the paper) yesterday. He will merge  WavLM into S3PRL, and he also mentions the different version FAIRSEQ issue. Our initial plan is to use a simple Pytorch code for the PR.
 @bagustris, will you merge the unispeechSat models into the S3PRL?

**Comment by bagustris** [comment] 2021-11-11 05:06
Thank's @MarkWuNLP!

I'll try.

I have working code for unispeechSat base, base+, and large with huggingface config. I also have this problem with fairseq version if I implement it on the direct model (without huggingface). So I implement it with the already uploaded model in the Huggingface. If you could upload the model into Huggingface, I think the steps could be simpler (I just copy the wav2vec2 directory from upstream and modify it accordingly). 

Let me test one of the official downstream tasks before I make a PR.

**Comment by Sanyuan-Chen** [comment] 2021-11-12 11:13
Hi @bagustris and @leo19941227 ,
I have made a pull request #246  to merge WavLM model into S3PRL, and tested it on QbE task.
Please take a review and let me know if you have any questions.

**Comment by leo19941227** [comment] 2021-11-13 11:11
Thanks @Sanyuan-Chen !
I have merged the PR for WavLM.

**Comment by leo19941227** [comment] 2021-11-15 10:39
Hi @bagustris !

Thanks for planning to merge Unispeech-SAT!
Since recently we wish to study these very new SOTA models on more speech tasks, may I ask about your schedule on sending the PR?
Thanks!

**Comment by bagustris** [comment] 2021-11-15 22:13
Hopefully this week, sorry for the long delay!

I can confirm their claimed result on ER task (with a few eval steps) but need to confirm the base and base+ model.
Or I can directly make a PR.

**Comment by leo19941227** [comment] 2021-11-16 03:05
Oh no problem! Thanks for confirming the correctness.
I would suggest to make the PR directly so I can also help to test on other tasks :)

**Comment by MarkWuNLP** [comment] 2021-11-16 03:29
Hi @bagustris, 
   For your convenience, I pasted our fine-tuning hyper-parameters here. You can follow our settings in Base and Base+ to reproduce the results you need. Thank you for the UniSpeech-SAT integration!


\begin{table}[t]
% \small
\centering
% \begin{center}
\caption{Hyperparamenters of fine-tuning UniSpeech-SAT models on SUPERB downstream tasks. 
LR and BSZ denote leaning rate and batch size respectively.
}\label{table:superb_hyper}
\resizebox{0.45\textwidth}{!}{
\begin{tabular}{l|cc|cc|cc|cc}
\toprule
\multirow{2}{*}{Task}    & \multicolumn{2}{c|}{Base} & \multicolumn{2}{c|}{Base+} & \multicolumn{2}{c}{Large} & \multicolumn{2}{c}{Large+} \\ 
    % \hline
    & LR & BSZ   & LR & BSZ  & LR & BSZ & LR & BSZ \\ \hline
SID &  1e-1   & 512 & 1e-1 &  512  & 1e-1 & 512 & 1e-1 & 512  \\ 
ASV &  5e-5 & 512 & 1e-4  & 512  & 1e-4 &  512 & 5e-5 & 512 \\ 
SD & 1e-3 & 256  & 1e-3 &  256 & 5e-3 &  256  & 1e-3 & 256 \\ 
PR & 1e-3 & 128  & 1e-4 & 128  & 1e-4 & 128 & 1e-4 & 128 \\ 
ASR & 5e-4 &  128 & 1e-4 & 128  &  1e-4 & 128 & 1e-4 & 128   \\
KS & 1e-5 &  512 & 1e-5 &  512 &  1e-5  &  512 & 1e-5 & 512 \\
IC & 5e-5 & 128  & 1e-4 & 128  &  1e-4 & 128 & 1e-3 & 128   \\
SF & 2e-4 & 128  & 1e-4 & 128  &  1e-4  &  128 & 5e-5 & 128 \\
ER & 5e-5 & 32  & 5e-5 & 32  &  5e-5  &  32 & 1e-5 & 32 \\
\bottomrule
\end{tabular}}
% \end{center}
\end{table}

**Comment by leo19941227** [comment] 2021-11-27 15:36
Both WavLM and Unispeech are not merged into the master branch.
I am closing this issue.
Thanks @Sanyuan-Chen and @MarkWuNLP again for your great contribution!

**Closed by leo19941227** 2021-11-27 15:36 UTC

**Comment by bagustris** [comment] 2021-11-29 01:39
Perfect! Amazing works.

Sorry for my PR, I didn't have time last two-weeks to implement the raw Unispeech-sat.
As for wavlm_large, can you double-check it again? I have no problem with `base` and `base_plus` of wavlm, 
but for the `large` version, torch compains: "EOFError: Ran out of input ."

**Comment by leo19941227** [comment] 2021-11-29 06:46
Hi @bagustris 

Can you try to run_downstream.py again with -r option. I believe this error might be due to incomplete download.

**Comment by leo19941227** [comment] 2021-11-29 06:50
Oh I did not notice you fix the problem in the latest PR. Let me check. Thanks!
