### ISSUE TITLE
run_downstream.py doesn't work

### ISSUE THREAD

**Issue by OG-algo** [s3prl/s3prl#87] opened 2021-02-17 17:21 UTC
I'm using the latest master branch build.

trying to run run_downstream.py I'm getting the following error for all available upstream models:
_"run_downstream.py: error: argument -u/--upstream: invalid choice: 'npc' (choose from )"_

after a little bit of investigating I found that the upstreams variable in s3prl\run_downstream.py -> line 38 is an always empty list.

farther into the search i thought that rplacing (in in s3prl\hubconf.py -> line 24)
**original line**: module_name = '.'.join(str(hubconf).split('.')[:-1]).replace('/', '.')
with
**fixed line**: module_name = '.'.join(str(hubconf).split('\\')[:-1]).replace('/', '.')

may fix this problem but yet, I noticed that 'callable(_variable)' (line 34) is always False.

is this an error in the code?

Thanks

**Comment by leo19941227** [comment] 2021-02-18 00:03
Hey,

Thanks for pointing out. I guess this might be a platform dependent behavior, since I do not encounter problem on all my Linux machines. Can you share the OS you are using?

**Comment by OG-algo** [comment] 2021-02-18 08:29
I'm using windows 10

**Comment by andi611** [comment] 2021-03-02 08:50
Hi, I think this is a platform-dependent issue and not an error in the code.
Currently, we are not able to reproduce this situation, I will close this for now.

**Closed by andi611** 2021-03-02 08:50 UTC

**Comment by leo19941227** [comment] 2021-03-02 15:34
Actually this is indeed a bug for Windows users, since we are assuming that directories are separated by `/` which is always is case on Linux but not on Windows. However, since we are not planning to support Windows in near future, we are still closing this issue. Feel free to re-open the issue if you really need to run experiments on Windows and wish to a future support. However, I will strongly suggest switching to Linux machine for this kind of DL experiments.
