### ISSUE TITLE
Is this required for the SS and SE task? assert abs(feat_list[i].size(0) - length_list[i]) < 5. I am getting this error for wav2vec

### ISSUE THREAD

**Issue by raotnameh** [s3prl/s3prl#519] opened 2023-12-09 07:02 UTC
Traceback (most recent call last):                                                                                                                                                 | 0/1738 [00:00<?, ?it/s]
  File "/raid/home/rajivratn/hemant/superb/s3prl_1st/s3prl/run_downstream.py", line 220, in <module>
    main()
  File "/raid/home/rajivratn/hemant/superb/s3prl_1st/s3prl/run_downstream.py", line 216, in main
    eval(f'runner.{args.mode}')()
  File "/raid/home/rajivratn/hemant/superb/s3prl_1st/s3prl/downstream/runner.py", line 308, in train
    loss = self.downstream.model(
  File "/raid/home/rajivratn/miniconda3/envs/SE/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/raid/home/rajivratn/miniconda3/envs/SE/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/raid/home/rajivratn/hemant/superb/s3prl_1st/s3prl/downstream/separation_stft/expert.py", line 258, in forward
    features = match_length(features, feat_length)
  File "/raid/home/rajivratn/hemant/superb/s3prl_1st/s3prl/downstream/separation_stft/expert.py", line 42, in match_length
    assert abs(feat_list[i].size(0) - length_list[i]) < 5

**Comment by leo19941227** [comment] 2023-12-10 17:42
This is not required, however this means something is off, since the expected length from the wav2vec is too different from our prepared target labels' length. I will check it. (It is weird since we ran wav2vec before and I do now remember this happened before.)

**Comment by raotnameh** [comment] 2023-12-18 05:58
Hi, any update on this? I need to run the experiments for a paper. Thanks.

**Comment by leo19941227** [comment] 2023-12-21 18:08
Hi @raotnameh ,

Sorry for the delay. However, I can not reproduce the error so far.
Is this error easy to identify or reproduce?

**Comment by leo19941227** [comment] 2023-12-21 18:09
Specifically, does it happen at the middle/end of the training, or it happen at the start of the training?

**Comment by raotnameh** [comment] 2023-12-21 18:37
@leo19941227 Apologies, I made a mistake in my code which caused the input from the upstream be of fixed length 1. I corrected the mistake and now it is not giving the error. Thank you for the help.

**Comment by leo19941227** [comment] 2023-12-21 18:52
Oh, no problem. Thanks for letting me know. I am closing the issue.

**Closed by leo19941227** 2023-12-21 18:52 UTC
