### ISSUE TITLE
Downstream setting problem

### ISSUE THREAD

**Issue by toco2270853** [s3prl/s3prl#120] opened 2021-06-02 03:31 UTC
Sorry for the simple question, I'm just wondering when following the instruction to run the downstream task, whether the result directly comparable to the result reported in SUPERB benchmark(e.g. strictly use the same train-val-dev split, downstream configuration...), or there may be some subtle difference?

**Comment by leo19941227** [comment] 2021-06-02 07:12
Hi!

Thank you for the interest. It will be directly comparable since it is exactly the same code we used to run the SUPERB experiment without any refactoring.

Sincerely,
Leo.

**Comment by andi611** [comment] 2021-06-02 07:37
Hi,
**The instructions and configs are identical to the SUPERB benchmark** (i.e. strictly using the same train-val-dev split, downstream configuration... etc.) 

However, **you may want to explore and tune the learning rate** (since every "upstream and downstream pair" may prefer different learning rates). For example, in our SUPERB paper, for every upstream model, we explore five different learning rates for each downstream task. Thus, if you are getting slightly different results than the SUPERB numbers, you are most likely using a different learning rate than us.

Please let us know if you have any further problems reproducing our results. I will close this issue for now, if you have any questions you can re-open it.

Thanks,
Andy

**Closed by andi611** 2021-06-02 07:37 UTC
Labels: paper / research
